import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Suspense } from 'react';
import { LoaderProvider } from '@/components/GlobalLoader';
import { NavigationLoader } from '@/components/NavigationLoader';
import Loading from '@/components/Loading';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoaderProvider>
          <NavigationLoader />
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </LoaderProvider>
      </body>
    </html>
  );
}
