import { Aleo } from "next/font/google";
import "./globals.css";

const aleo = Aleo({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-aleo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${aleo.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

